### ISSUE TITLE
Remember me checkbox at login isn't working

### ISSUE THREAD

**Issue by rbrezynski** [Chaseshak/BadgerNet#60]
Testing in Safari on live site.
Log in as a valid user and check remember me checkbox.
Log out again and observe that no email is stored in the sign in section

**Comment by Chaseshak** [comment]
@rbrezynski The `Remember Me` checkbox is not for remembering email. It is for persisting the user session for a period of time. I think the default may be infinite unless the user logs out or logs in somewhere else.

The expected behavior is that you shouldn't have to log back in after closing the tab or browser window.

**Comment by rbrezynski** [comment]
Got it! Thanks. I will close this issue
